---
title: "Quarto"
execute: 
    echo: true
format:
    pdf: 
        toc: false
        number-sections: false
        CJKmainfont: STKaiti
editor_options: 
  chunk_output_type: console
---

A demo of `Quarto`.

```{r}
#| message: false
#| warning: false
source("database.R")
```

Currently we have a data frame with `r nrow(dat)` rows.

We can do some R function. 

```{r rsection}
library(dplyr)
dat |> 
    summarise(
        min_carat = min(carat), 
        max_carat = max(carat)
        ) |> 
    knitr::kable()
```

We can also do some Python function.

```{r, include=FALSE}
library(reticulate)
use_condaenv("base")
```

```{python pysection}
import pandas 
from IPython.display import Markdown
from tabulate import tabulate
res = r.dat.agg(min_carat=('carat', min), max_carat=('carat', max))
Markdown(tabulate(res))
```

\newpage Needless to say, we can do some *beautiful* plot. 

```{r rplot}
library(ggplot2)
dat |> 
    ggplot(aes(carat, price, col = color)) +
    geom_point(alpha = 0.7) + 
    scale_y_continuous(labels = scales::dollar) + 
    scale_color_brewer(palette = "Dark2") + 
    theme_light() + 
    theme(legend.position = "top") +
    labs(x = "Carat", y = "Price", col = "Color")
```

